// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vjecahooihxrofwmdbix.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZqZWNhaG9vaWh4cm9md21kYml4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY0NjY1MTYsImV4cCI6MjA5MjA0MjUxNn0.aWUcOADes8Nx8RJaKIsJGH2w7vVFeEoeyqZcKgSUapY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});